export const AGREGAR_PERSONA = 'AGREGAR_PERSONA';
export const COMENZAR_EDICION_PERSONA = 'COMENZAR_EDICION_PERSONA';
export const COMENZAR_DESCARGA_PERSONAL = 'COMENZAR_DESCARGA_PERSONAL';
export const AGREGAR_PERSONA_EXITO = 'AGREGAR_PERSONA_EXITO';
export const DESCARGA_PERSONAL_EXITO = 'DESCARGA_PERSONAL_EXITO';
export const OBTENER_PERSONA_EDITAR = 'OBTENER_PERSONA_EDITAR';
export const PERSONA_EDITADA_EXITO = 'PERSONA_EDITADA_EXITO';
