export const AGREGAR_PERSONA = 'AGREGAR_PERSONA';
export const COMENZAR_EDICION_PERSONA = 'COMENZAR_EDICION_PERSONA';
export const COMENZAR_DESCARGA_PERSONAL = 'COMENZAR_DESCARGA_PERSONAL';
export const AGREGAR_PERSONA_EXITO = 'AGREGAR_PERSONA_EXITO';
export const DESCARGA_PERSONAL_EXITO = 'DESCARGA_PERSONAL_EXITO';
export const OBTENER_PERSONA_EDITAR = 'OBTENER_PERSONA_EDITAR';
export const PERSONA_EDITADA_EXITO = 'PERSONA_EDITADA_EXITO';
export const OBTENER_PERSONA_ELIMINAR = 'OBTENER_PERSONA_ELIMINAR';
export const PERSONA_ELIMINADA_EXITO = 'PERSONA_ELIMINADA_EXITO';
export const PERSONA_ELIMINADA_ERROR = 'PERSONA_ELIMINADA_ERROR';
export const AGREGAR_PERSONA_ERROR = 'AGREGAR_PERSONA_ERROR';
export const DESCARGA_PERSONAL_ERROR = 'DESCARGA_PERSONAL_ERROR';
export const PERSONA_EDITADA_ERROR = 'PERSONA_EDITADA_ERROR';




    
